name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get commit ID
        id: commit-id
        shell: bash
        run: |
          COMMIT_SHA="${{ github.sha }}"
          echo "::set-output name=short_commit_id::$(echo ${COMMIT_SHA::10})"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.version=${{ steps.commit_id.outputs.short_commit_id }}
          platforms: linux/amd64